language: node_js
node_js:
  - "4"
  - "6"
os:
  - linux
  - osx
osx_image: xcode8
install:
  - npm install
  - npm run lint
  - npm run build
script:
  - npm run test-build
# cache:
#   directories:
#     - node_modules
